false_beliefs = [
    "We only use 10% of our brains",
    "The Great Wall of China is visible from space",
    "Goldfish have a 3-second memory",
    "Cracking your knuckles causes arthritis",
    "Lightning never strikes the same place twice",
    "Bats are blind",
    "Bulls are angered by the color red",
    "Humans have five senses",
    "Sugar makes children hyperactive",
    "You need to wait 24 hours to file a missing person report",
    "Shaving makes hair grow back thicker",
    "We swallow eight spiders a year in our sleep",
    "Touching a baby bird will make its mother reject it",
    "Napoleon was unusually short",
    "Vikings wore horned helmets",
    "Chameleons change color to blend in with surroundings",
    "Dogs see in black and white",
    "You lose most body heat through your head",
    "Eating before swimming causes cramps",
    "Dropping a penny from a skyscraper could kill someone",
    "Einstein failed math in school",
    "The tongue has distinct taste zones",
    "Humans evolved from chimpanzees",
    "You need to drink exactly eight glasses of water a day",
    "Hair and nails continue to grow after death",
    "Bananas grow on trees",
    "Ostriches bury their heads in the sand",
    "Sushi means raw fish",
    "Mount Everest is the tallest mountain on Earth measured from base to peak",
    "Blood is blue inside the body",
    "Toilets flush in opposite directions in different hemispheres",
    "Thomas Edison invented the light bulb",
    "It takes seven years to digest swallowed gum",
    "Carrots improve your eyesight",
    "Alcohol kills brain cells",
    "The forbidden fruit in the Bible was an apple",
    "Columbus discovered America",
    "Diamonds are made from compressed coal",
    "Goldfish can only grow to the size of their bowl",
    "You can see the Great Pyramid from space",
    "Fortune cookies are a Chinese tradition",
    "Black belts have to register their hands as weapons",
    "Eating chocolate causes acne",
    "People in the Middle Ages thought the Earth was flat",
    "Daddy longlegs are the most venomous spiders",
    "Seasons are caused by Earth's distance from the Sun",
    "Camels store water in their humps",
    "Lemmings commit mass suicide by jumping off cliffs",
    "SOS stands for Save Our Souls",
    "A dog's mouth is cleaner than a human's",
    "Muscle turns into fat when you stop exercising",
    "Your fingernails are made of the same material as hair",  # this one's actually true, maybe borderline
    "Vitamin C cures the common cold",
    "MSG is bad for you",
    "Reading in dim light ruins your eyesight",
    "Waking a sleepwalker is dangerous",
    "George Washington had wooden teeth",
    "Coffee stunts your growth",
    "Cells fully replace themselves every seven years",
    "Microwaves cook food from the inside out",
    "The Sahara is the largest desert on Earth",
    "Centipedes have exactly 100 legs",
    "Milk increases mucus production",
    "Twinkies last forever",
    "Elephants are afraid of mice",
    "You eat a certain number of insects per year without knowing",
    "The Coriolis effect determines which way your bathtub drains",
    "Different parts of the tongue taste different flavors",
    "Adding salt to water makes it boil faster",
    "Starfish are fish",
    "Peanuts are nuts",
    "Tomatoes were once considered poisonous in Europe because of the fruit itself",
    "Antibiotics kill viruses",
    "The dark side of the Moon is always dark",
    "Eskimos have hundreds of words for snow",
    "Humans and dinosaurs coexisted",
    "Chlorine in pools turns your eyes red",
    "A mother bird will abandon chicks if you touch the nest",
    "Poinsettias are highly toxic",
    "Sharks don't get cancer",
    "Stretching before exercise prevents injury",
    "Oil added to pasta water stops pasta from sticking",
    "Irregardless is not a word",
    "Glass is a slow-moving liquid",
    "The iron maiden was a medieval torture device",
    "You can get a cold from being cold",
    "Nero fiddled while Rome burned",
    "Marie Antoinette said 'Let them eat cake'",
    "Frankenstein is the name of the monster",
    "Spinach is an exceptionally good source of iron",
    "Coffee dehydrates you",
    "Bears hibernate all winter without waking",
    "Redheads are going extinct",
    "Polygraph tests reliably detect lies",
    "The five-second rule for dropped food is scientifically valid",
    "Humans are the only animals that use tools",
    "You should tilt your head back during a nosebleed",
    "Thomas Crapper invented the flush toilet",
    "There is no gravity in space",
    "Left-brained people are logical and right-brained people are creative",
    "Vaccines cause autism",
]